[package]
name = "hd2re"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binrw = "0.13.*"
speedy = "0.8.*"
magika = { version = "0.1.0-dev", path = "../magika/rust" }
onnxruntime = "0.0.14"
